#!/bin/sh

DIR="example-data"
A="$DIR/in-verbs.txt"
B="$DIR/in-nouns+adjectives.txt"
C="$DIR/db-verbs.txt"
D="$DIR/db-nouns.txt"
E="$DIR/db-adjectives.txt"
F="$DIR/out.txt"

./gradlew run -PappArgs="['$A', '$B', '$C', '$D', '$E', '$F']"
